spring:
  application:
    name: expense-tracker-api

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/expense_tracker?useSSL=false&serverTimezone=UTC}
    username: ${SPRING_DATASOURCE_USERNAME:root}
    password: ${SPRING_DATASOURCE_PASSWORD:password}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
    show-sql: true

server:
  port: 8080